insert into public.airports (
  iata_code,
  name,
  city,
  state,
  country,
  region_code,
  region_name,
  latitude,
  longitude,
  is_commercial
)
values
  ('ATL', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta', 'GA', 'US', 'GA', 'Georgia', 33.6407, -84.4277, true),
  ('LAX', 'Los Angeles International Airport', 'Los Angeles', 'CA', 'US', 'CA', 'California', 33.9416, -118.4085, true),
  ('ORD', 'Chicago O''Hare International Airport', 'Chicago', 'IL', 'US', 'IL', 'Illinois', 41.9742, -87.9073, true),
  ('DFW', 'Dallas/Fort Worth International Airport', 'Dallas-Fort Worth', 'TX', 'US', 'TX', 'Texas', 32.8998, -97.0403, true),
  ('DEN', 'Denver International Airport', 'Denver', 'CO', 'US', 'CO', 'Colorado', 39.8561, -104.6737, true),
  ('JFK', 'John F. Kennedy International Airport', 'New York', 'NY', 'US', 'NY', 'New York', 40.6413, -73.7781, true),
  ('EWR', 'Newark Liberty International Airport', 'Newark', 'NJ', 'US', 'NJ', 'New Jersey', 40.6895, -74.1745, true),
  ('SFO', 'San Francisco International Airport', 'San Francisco', 'CA', 'US', 'CA', 'California', 37.6213, -122.379, true),
  ('LAS', 'Harry Reid International Airport', 'Las Vegas', 'NV', 'US', 'NV', 'Nevada', 36.084, -115.1537, true),
  ('SEA', 'Seattle-Tacoma International Airport', 'Seattle', 'WA', 'US', 'WA', 'Washington', 47.4502, -122.3088, true),
  ('MCO', 'Orlando International Airport', 'Orlando', 'FL', 'US', 'FL', 'Florida', 28.4312, -81.3081, true),
  ('MIA', 'Miami International Airport', 'Miami', 'FL', 'US', 'FL', 'Florida', 25.7959, -80.287, true),
  ('CLT', 'Charlotte Douglas International Airport', 'Charlotte', 'NC', 'US', 'NC', 'North Carolina', 35.2144, -80.9473, true),
  ('PHX', 'Phoenix Sky Harbor International Airport', 'Phoenix', 'AZ', 'US', 'AZ', 'Arizona', 33.4352, -112.0101, true),
  ('IAH', 'George Bush Intercontinental Airport', 'Houston', 'TX', 'US', 'TX', 'Texas', 29.9902, -95.3368, true),
  ('BOS', 'Boston Logan International Airport', 'Boston', 'MA', 'US', 'MA', 'Massachusetts', 42.3656, -71.0096, true),
  ('MSP', 'Minneapolis-Saint Paul International Airport', 'Minneapolis-Saint Paul', 'MN', 'US', 'MN', 'Minnesota', 44.8848, -93.2223, true),
  ('DTW', 'Detroit Metropolitan Wayne County Airport', 'Detroit', 'MI', 'US', 'MI', 'Michigan', 42.2162, -83.3554, true),
  ('PHL', 'Philadelphia International Airport', 'Philadelphia', 'PA', 'US', 'PA', 'Pennsylvania', 39.8744, -75.2424, true),
  ('LGA', 'LaGuardia Airport', 'New York', 'NY', 'US', 'NY', 'New York', 40.7769, -73.874, true),
  ('FLL', 'Fort Lauderdale-Hollywood International Airport', 'Fort Lauderdale', 'FL', 'US', 'FL', 'Florida', 26.0742, -80.1506, true),
  ('BWI', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore', 'MD', 'US', 'MD', 'Maryland', 39.1774, -76.6684, true),
  ('SLC', 'Salt Lake City International Airport', 'Salt Lake City', 'UT', 'US', 'UT', 'Utah', 40.7899, -111.9791, true),
  ('DCA', 'Ronald Reagan Washington National Airport', 'Washington', 'DC', 'US', 'DC', 'Washington DC', 38.8512, -77.0402, true),
  ('IAD', 'Washington Dulles International Airport', 'Dulles', 'VA', 'US', 'VA', 'Virginia', 38.9531, -77.4565, true),
  ('SAN', 'San Diego International Airport', 'San Diego', 'CA', 'US', 'CA', 'California', 32.7338, -117.1933, true),
  ('TPA', 'Tampa International Airport', 'Tampa', 'FL', 'US', 'FL', 'Florida', 27.9755, -82.5332, true),
  ('HNL', 'Daniel K. Inouye International Airport', 'Honolulu', 'HI', 'US', 'HI', 'Hawaii', 21.3245, -157.9251, true),
  ('PDX', 'Portland International Airport', 'Portland', 'OR', 'US', 'OR', 'Oregon', 45.5898, -122.5951, true),
  ('AUS', 'Austin-Bergstrom International Airport', 'Austin', 'TX', 'US', 'TX', 'Texas', 30.1975, -97.6664, true),
  ('BNA', 'Nashville International Airport', 'Nashville', 'TN', 'US', 'TN', 'Tennessee', 36.1263, -86.6774, true),
  ('DAL', 'Dallas Love Field', 'Dallas', 'TX', 'US', 'TX', 'Texas', 32.8471, -96.8518, true),
  ('HOU', 'William P. Hobby Airport', 'Houston', 'TX', 'US', 'TX', 'Texas', 29.6454, -95.2789, true),
  ('MDW', 'Chicago Midway International Airport', 'Chicago', 'IL', 'US', 'IL', 'Illinois', 41.7868, -87.7522, true),
  ('OAK', 'San Francisco Bay Oakland International Airport', 'Oakland', 'CA', 'US', 'CA', 'California', 37.7126, -122.2197, true),
  ('SJC', 'San Jose Mineta International Airport', 'San Jose', 'CA', 'US', 'CA', 'California', 37.3639, -121.9289, true),
  ('SMF', 'Sacramento International Airport', 'Sacramento', 'CA', 'US', 'CA', 'California', 38.6954, -121.5908, true),
  ('SNA', 'John Wayne Airport', 'Orange County', 'CA', 'US', 'CA', 'California', 33.6757, -117.8682, true),
  ('ONT', 'Ontario International Airport', 'Ontario', 'CA', 'US', 'CA', 'California', 34.0559, -117.6012, true),
  ('BUR', 'Hollywood Burbank Airport', 'Burbank', 'CA', 'US', 'CA', 'California', 34.2007, -118.3587, true),
  ('RNO', 'Reno-Tahoe International Airport', 'Reno', 'NV', 'US', 'NV', 'Nevada', 39.4991, -119.7681, true),
  ('ABQ', 'Albuquerque International Sunport', 'Albuquerque', 'NM', 'US', 'NM', 'New Mexico', 35.0402, -106.6092, true),
  ('ELP', 'El Paso International Airport', 'El Paso', 'TX', 'US', 'TX', 'Texas', 31.8072, -106.3778, true),
  ('SAT', 'San Antonio International Airport', 'San Antonio', 'TX', 'US', 'TX', 'Texas', 29.5337, -98.4698, true),
  ('OKC', 'Will Rogers World Airport', 'Oklahoma City', 'OK', 'US', 'OK', 'Oklahoma', 35.3931, -97.6007, true),
  ('TUL', 'Tulsa International Airport', 'Tulsa', 'OK', 'US', 'OK', 'Oklahoma', 36.1984, -95.8881, true),
  ('MCI', 'Kansas City International Airport', 'Kansas City', 'MO', 'US', 'MO', 'Missouri', 39.2976, -94.7139, true),
  ('STL', 'St. Louis Lambert International Airport', 'St. Louis', 'MO', 'US', 'MO', 'Missouri', 38.7499, -90.3748, true),
  ('MKE', 'Milwaukee Mitchell International Airport', 'Milwaukee', 'WI', 'US', 'WI', 'Wisconsin', 42.9472, -87.8966, true),
  ('CLE', 'Cleveland Hopkins International Airport', 'Cleveland', 'OH', 'US', 'OH', 'Ohio', 41.4117, -81.8498, true),
  ('CMH', 'John Glenn Columbus International Airport', 'Columbus', 'OH', 'US', 'OH', 'Ohio', 39.998, -82.8919, true),
  ('CVG', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati', 'KY', 'US', 'KY', 'Kentucky', 39.0488, -84.6678, true),
  ('IND', 'Indianapolis International Airport', 'Indianapolis', 'IN', 'US', 'IN', 'Indiana', 39.7169, -86.2956, true),
  ('PIT', 'Pittsburgh International Airport', 'Pittsburgh', 'PA', 'US', 'PA', 'Pennsylvania', 40.4915, -80.2329, true),
  ('RDU', 'Raleigh-Durham International Airport', 'Raleigh-Durham', 'NC', 'US', 'NC', 'North Carolina', 35.8801, -78.788, true),
  ('CHS', 'Charleston International Airport', 'Charleston', 'SC', 'US', 'SC', 'South Carolina', 32.8986, -80.0405, true),
  ('SAV', 'Savannah/Hilton Head International Airport', 'Savannah', 'GA', 'US', 'GA', 'Georgia', 32.1276, -81.2021, true),
  ('JAX', 'Jacksonville International Airport', 'Jacksonville', 'FL', 'US', 'FL', 'Florida', 30.4941, -81.6879, true),
  ('RSW', 'Southwest Florida International Airport', 'Fort Myers', 'FL', 'US', 'FL', 'Florida', 26.5362, -81.7552, true),
  ('PBI', 'Palm Beach International Airport', 'West Palm Beach', 'FL', 'US', 'FL', 'Florida', 26.6832, -80.0956, true),
  ('SRQ', 'Sarasota Bradenton International Airport', 'Sarasota', 'FL', 'US', 'FL', 'Florida', 27.3954, -82.5544, true),
  ('MSY', 'Louis Armstrong New Orleans International Airport', 'New Orleans', 'LA', 'US', 'LA', 'Louisiana', 29.9934, -90.258, true),
  ('MEM', 'Memphis International Airport', 'Memphis', 'TN', 'US', 'TN', 'Tennessee', 35.0424, -89.9767, true),
  ('TYS', 'McGhee Tyson Airport', 'Knoxville', 'TN', 'US', 'TN', 'Tennessee', 35.811, -83.994, true),
  ('SDF', 'Louisville Muhammad Ali International Airport', 'Louisville', 'KY', 'US', 'KY', 'Kentucky', 38.1744, -85.736, true),
  ('BHM', 'Birmingham-Shuttlesworth International Airport', 'Birmingham', 'AL', 'US', 'AL', 'Alabama', 33.5629, -86.7535, true),
  ('HSV', 'Huntsville International Airport', 'Huntsville', 'AL', 'US', 'AL', 'Alabama', 34.6372, -86.7751, true),
  ('JAN', 'Jackson-Medgar Wiley Evers International Airport', 'Jackson', 'MS', 'US', 'MS', 'Mississippi', 32.3112, -90.0759, true),
  ('LIT', 'Bill and Hillary Clinton National Airport', 'Little Rock', 'AR', 'US', 'AR', 'Arkansas', 34.7294, -92.2243, true),
  ('OMA', 'Eppley Airfield', 'Omaha', 'NE', 'US', 'NE', 'Nebraska', 41.3032, -95.8941, true),
  ('DSM', 'Des Moines International Airport', 'Des Moines', 'IA', 'US', 'IA', 'Iowa', 41.534, -93.6631, true),
  ('ICT', 'Wichita Dwight D. Eisenhower National Airport', 'Wichita', 'KS', 'US', 'KS', 'Kansas', 37.6499, -97.4331, true),
  ('XNA', 'Northwest Arkansas National Airport', 'Bentonville/Fayetteville', 'AR', 'US', 'AR', 'Arkansas', 36.2819, -94.3068, true),
  ('BOI', 'Boise Airport', 'Boise', 'ID', 'US', 'ID', 'Idaho', 43.5644, -116.2228, true),
  ('ANC', 'Ted Stevens Anchorage International Airport', 'Anchorage', 'AK', 'US', 'AK', 'Alaska', 61.1743, -149.9964, true),
  ('FAI', 'Fairbanks International Airport', 'Fairbanks', 'AK', 'US', 'AK', 'Alaska', 64.8151, -147.8563, true),
  ('OGG', 'Kahului Airport', 'Kahului', 'HI', 'US', 'HI', 'Hawaii', 20.8986, -156.4305, true),
  ('KOA', 'Ellison Onizuka Kona International Airport', 'Kailua-Kona', 'HI', 'US', 'HI', 'Hawaii', 19.7388, -156.0456, true),
  ('LIH', 'Lihue Airport', 'Lihue', 'HI', 'US', 'HI', 'Hawaii', 21.976, -159.3389, true),
  ('BTV', 'Patrick Leahy Burlington International Airport', 'Burlington', 'VT', 'US', 'VT', 'Vermont', 44.4719, -73.1533, true),
  ('PWM', 'Portland International Jetport', 'Portland', 'ME', 'US', 'ME', 'Maine', 43.6462, -70.3093, true),
  ('MHT', 'Manchester-Boston Regional Airport', 'Manchester', 'NH', 'US', 'NH', 'New Hampshire', 42.9326, -71.4357, true),
  ('PVD', 'Rhode Island T. F. Green International Airport', 'Providence', 'RI', 'US', 'RI', 'Rhode Island', 41.724, -71.4282, true),
  ('BDL', 'Bradley International Airport', 'Hartford', 'CT', 'US', 'CT', 'Connecticut', 41.9389, -72.6832, true),
  ('ALB', 'Albany International Airport', 'Albany', 'NY', 'US', 'NY', 'New York', 42.7483, -73.8017, true),
  ('BUF', 'Buffalo Niagara International Airport', 'Buffalo', 'NY', 'US', 'NY', 'New York', 42.9405, -78.7322, true),
  ('ROC', 'Frederick Douglass Greater Rochester International Airport', 'Rochester', 'NY', 'US', 'NY', 'New York', 43.1189, -77.6724, true),
  ('SYR', 'Syracuse Hancock International Airport', 'Syracuse', 'NY', 'US', 'NY', 'New York', 43.1112, -76.1063, true),
  ('ORF', 'Norfolk International Airport', 'Norfolk', 'VA', 'US', 'VA', 'Virginia', 36.8946, -76.2012, true),
  ('RIC', 'Richmond International Airport', 'Richmond', 'VA', 'US', 'VA', 'Virginia', 37.5052, -77.3197, true),
  ('GSP', 'Greenville-Spartanburg International Airport', 'Greenville-Spartanburg', 'SC', 'US', 'SC', 'South Carolina', 34.8957, -82.2189, true),
  ('MYR', 'Myrtle Beach International Airport', 'Myrtle Beach', 'SC', 'US', 'SC', 'South Carolina', 33.6797, -78.9283, true),
  ('ILM', 'Wilmington International Airport', 'Wilmington', 'NC', 'US', 'NC', 'North Carolina', 34.2706, -77.9026, true),
  ('AVL', 'Asheville Regional Airport', 'Asheville', 'NC', 'US', 'NC', 'North Carolina', 35.4362, -82.5418, true),
  ('DAY', 'Dayton International Airport', 'Dayton', 'OH', 'US', 'OH', 'Ohio', 39.9024, -84.2194, true),
  ('GRR', 'Gerald R. Ford International Airport', 'Grand Rapids', 'MI', 'US', 'MI', 'Michigan', 42.8808, -85.5228, true),
  ('FNT', 'Bishop International Airport', 'Flint', 'MI', 'US', 'MI', 'Michigan', 42.9654, -83.7436, true),
  ('MSN', 'Dane County Regional Airport', 'Madison', 'WI', 'US', 'WI', 'Wisconsin', 43.1399, -89.3375, true),
  ('FAR', 'Hector International Airport', 'Fargo', 'ND', 'US', 'ND', 'North Dakota', 46.9207, -96.8158, true),
  ('BIS', 'Bismarck Municipal Airport', 'Bismarck', 'ND', 'US', 'ND', 'North Dakota', 46.7727, -100.746, true),
  ('FSD', 'Sioux Falls Regional Airport', 'Sioux Falls', 'SD', 'US', 'SD', 'South Dakota', 43.582, -96.7419, true),
  ('RAP', 'Rapid City Regional Airport', 'Rapid City', 'SD', 'US', 'SD', 'South Dakota', 44.0453, -103.0574, true),
  ('BIL', 'Billings Logan International Airport', 'Billings', 'MT', 'US', 'MT', 'Montana', 45.8077, -108.5429, true),
  ('BZN', 'Bozeman Yellowstone International Airport', 'Bozeman', 'MT', 'US', 'MT', 'Montana', 45.7775, -111.153, true),
  ('JAC', 'Jackson Hole Airport', 'Jackson', 'WY', 'US', 'WY', 'Wyoming', 43.6073, -110.7377, true),
  ('CPR', 'Casper/Natrona County International Airport', 'Casper', 'WY', 'US', 'WY', 'Wyoming', 42.908, -106.4645, true),
  ('PSP', 'Palm Springs International Airport', 'Palm Springs', 'CA', 'US', 'CA', 'California', 33.8297, -116.5067, true),
  ('FAT', 'Fresno Yosemite International Airport', 'Fresno', 'CA', 'US', 'CA', 'California', 36.7762, -119.7181, true),
  ('TUS', 'Tucson International Airport', 'Tucson', 'AZ', 'US', 'AZ', 'Arizona', 32.1161, -110.941, true),
  ('GEG', 'Spokane International Airport', 'Spokane', 'WA', 'US', 'WA', 'Washington', 47.6199, -117.5338, true),
  ('YYZ', 'Toronto Pearson International Airport', 'Toronto', 'ON', 'CA', 'ON', 'Ontario', 43.6777, -79.6248, true),
  ('YVR', 'Vancouver International Airport', 'Vancouver', 'BC', 'CA', 'BC', 'British Columbia', 49.1967, -123.1815, true),
  ('YUL', 'Montreal-Trudeau International Airport', 'Montreal', 'QC', 'CA', 'QC', 'Quebec', 45.4706, -73.7408, true),
  ('YYC', 'Calgary International Airport', 'Calgary', 'AB', 'CA', 'AB', 'Alberta', 51.1215, -114.0076, true),
  ('YEG', 'Edmonton International Airport', 'Edmonton', 'AB', 'CA', 'AB', 'Alberta', 53.3097, -113.58, true),
  ('YOW', 'Ottawa International Airport', 'Ottawa', 'ON', 'CA', 'ON', 'Ontario', 45.3225, -75.6692, true),
  ('YHZ', 'Halifax Stanfield International Airport', 'Halifax', 'NS', 'CA', 'NS', 'Nova Scotia', 44.8808, -63.5086, true),
  ('YWG', 'Winnipeg James Armstrong Richardson International Airport', 'Winnipeg', 'MB', 'CA', 'MB', 'Manitoba', 49.9099, -97.2399, true),
  ('YQB', 'Quebec City Jean Lesage International Airport', 'Quebec City', 'QC', 'CA', 'QC', 'Quebec', 46.7911, -71.3933, true),
  ('YXE', 'Saskatoon John G. Diefenbaker International Airport', 'Saskatoon', 'SK', 'CA', 'SK', 'Saskatchewan', 52.1708, -106.6997, true),
  ('YYJ', 'Victoria International Airport', 'Victoria', 'BC', 'CA', 'BC', 'British Columbia', 48.6469, -123.4258, true),
  ('YLW', 'Kelowna International Airport', 'Kelowna', 'BC', 'CA', 'BC', 'British Columbia', 49.9561, -119.3778, true),
  ('YQR', 'Regina International Airport', 'Regina', 'SK', 'CA', 'SK', 'Saskatchewan', 50.4319, -104.6658, true),
  ('YYT', 'St. John''s International Airport', 'St. John''s', 'NL', 'CA', 'NL', 'Newfoundland and Labrador', 47.6186, -52.7519, true),
  ('YQM', 'Greater Moncton Romeo LeBlanc International Airport', 'Moncton', 'NB', 'CA', 'NB', 'New Brunswick', 46.1122, -64.6786, true),
  ('YYG', 'Charlottetown Airport', 'Charlottetown', 'PE', 'CA', 'PE', 'Prince Edward Island', 46.29, -63.1211, true),
  ('YXY', 'Erik Nielsen Whitehorse International Airport', 'Whitehorse', 'YT', 'CA', 'YT', 'Yukon', 60.7096, -135.0672, true),
  ('YZF', 'Yellowknife Airport', 'Yellowknife', 'NT', 'CA', 'NT', 'Northwest Territories', 62.4628, -114.4403, true),
  ('YFB', 'Iqaluit Airport', 'Iqaluit', 'NU', 'CA', 'NU', 'Nunavut', 63.7564, -68.5558, true),
  ('YTZ', 'Billy Bishop Toronto City Airport', 'Toronto', 'ON', 'CA', 'ON', 'Ontario', 43.6275, -79.3962, true),
  ('YHM', 'John C. Munro Hamilton International Airport', 'Hamilton', 'ON', 'CA', 'ON', 'Ontario', 43.1736, -79.935, true),
  ('YKF', 'Region of Waterloo International Airport', 'Kitchener/Waterloo', 'ON', 'CA', 'ON', 'Ontario', 43.4608, -80.3786, true),
  ('YFC', 'Fredericton International Airport', 'Fredericton', 'NB', 'CA', 'NB', 'New Brunswick', 45.8689, -66.5372, true),
  ('YQX', 'Gander International Airport', 'Gander', 'NL', 'CA', 'NL', 'Newfoundland and Labrador', 48.9369, -54.5681, true),
  ('YDF', 'Deer Lake Regional Airport', 'Deer Lake', 'NL', 'CA', 'NL', 'Newfoundland and Labrador', 49.2108, -57.3914, true),
  ('YXS', 'Prince George Airport', 'Prince George', 'BC', 'CA', 'BC', 'British Columbia', 53.8894, -122.6789, true),
  ('YMM', 'Fort McMurray International Airport', 'Fort McMurray', 'AB', 'CA', 'AB', 'Alberta', 56.6533, -111.2219, true),
  ('YQU', 'Grande Prairie Airport', 'Grande Prairie', 'AB', 'CA', 'AB', 'Alberta', 55.1797, -118.885, true),
  ('YQT', 'Thunder Bay International Airport', 'Thunder Bay', 'ON', 'CA', 'ON', 'Ontario', 48.3719, -89.3239, true),
  ('YKA', 'Kamloops Airport', 'Kamloops', 'BC', 'CA', 'BC', 'British Columbia', 50.7022, -120.4444, true),
  ('YCD', 'Nanaimo Airport', 'Nanaimo', 'BC', 'CA', 'BC', 'British Columbia', 49.0549, -123.8702, true)
on conflict (iata_code) do update set
  name = excluded.name,
  city = excluded.city,
  state = excluded.state,
  country = excluded.country,
  region_code = excluded.region_code,
  region_name = excluded.region_name,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  is_commercial = excluded.is_commercial,
  is_active = true;

insert into public.rental_companies (name, type)
values
  ('Alamo', 'traditional_rental'),
  ('Avis', 'traditional_rental'),
  ('Budget', 'traditional_rental'),
  ('Dollar', 'traditional_rental'),
  ('Enterprise', 'traditional_rental'),
  ('Hertz', 'traditional_rental'),
  ('National', 'traditional_rental'),
  ('Sixt', 'traditional_rental'),
  ('Thrifty', 'traditional_rental'),
  ('Payless', 'traditional_rental'),
  ('Fox', 'traditional_rental'),
  ('Advantage', 'traditional_rental'),
  ('ACE', 'traditional_rental'),
  ('Routes', 'traditional_rental'),
  ('Economy', 'traditional_rental'),
  ('Europcar', 'traditional_rental'),
  ('NU Car Rentals', 'traditional_rental'),
  ('NextCar', 'traditional_rental'),
  ('U-Save', 'traditional_rental'),
  ('Green Motion', 'traditional_rental'),
  ('E-Z Rent-A-Car', 'traditional_rental'),
  ('Airport Van Rental', 'traditional_rental'),
  ('Silvercar', 'traditional_rental'),
  ('Zipcar', 'car_sharing'),
  ('Turo', 'peer_to_peer')
on conflict (name) do update set
  type = excluded.type,
  is_active = true;

insert into public.car_makes (name)
values
  ('Acura'),
  ('Alfa Romeo'),
  ('Audi'),
  ('BMW'),
  ('Buick'),
  ('Cadillac'),
  ('Chevrolet'),
  ('Chrysler'),
  ('Dodge'),
  ('Fiat'),
  ('Ford'),
  ('Genesis'),
  ('GMC'),
  ('Honda'),
  ('Hyundai'),
  ('Infiniti'),
  ('Jeep'),
  ('Kia'),
  ('Land Rover'),
  ('Lexus'),
  ('Lincoln'),
  ('Mazda'),
  ('Mercedes-Benz'),
  ('Mini'),
  ('Mitsubishi'),
  ('Nissan'),
  ('Polestar'),
  ('Porsche'),
  ('Ram'),
  ('Subaru'),
  ('Tesla'),
  ('Toyota'),
  ('Volkswagen'),
  ('Volvo')
on conflict (name) do update set is_active = true;

insert into public.car_models (make_id, name)
select cm.id, model.name
from public.car_makes cm
join (
  values
    ('Acura', 'ILX'),
    ('Acura', 'Integra'),
    ('Acura', 'TLX'),
    ('Acura', 'RDX'),
    ('Acura', 'MDX'),
    ('Alfa Romeo', 'Giulia'),
    ('Alfa Romeo', 'Stelvio'),
    ('Alfa Romeo', 'Tonale'),
    ('Audi', 'A3'),
    ('Audi', 'A4'),
    ('Audi', 'A5'),
    ('Audi', 'A6'),
    ('Audi', 'Q3'),
    ('Audi', 'Q5'),
    ('Audi', 'Q7'),
    ('Audi', 'Q8'),
    ('Audi', 'e-tron'),
    ('BMW', '2 Series'),
    ('BMW', '3 Series'),
    ('BMW', '4 Series'),
    ('BMW', '5 Series'),
    ('BMW', 'X1'),
    ('BMW', 'X2'),
    ('BMW', 'X3'),
    ('BMW', 'X5'),
    ('BMW', 'X7'),
    ('BMW', 'i4'),
    ('Buick', 'Encore'),
    ('Buick', 'Encore GX'),
    ('Buick', 'Envision'),
    ('Buick', 'Enclave'),
    ('Cadillac', 'CT4'),
    ('Cadillac', 'CT5'),
    ('Cadillac', 'XT4'),
    ('Cadillac', 'XT5'),
    ('Cadillac', 'XT6'),
    ('Cadillac', 'Escalade'),
    ('Cadillac', 'Lyriq'),
    ('Chevrolet', 'Spark'),
    ('Chevrolet', 'Malibu'),
    ('Chevrolet', 'Trax'),
    ('Chevrolet', 'Trailblazer'),
    ('Chevrolet', 'Equinox'),
    ('Chevrolet', 'Blazer'),
    ('Chevrolet', 'Traverse'),
    ('Chevrolet', 'Tahoe'),
    ('Chevrolet', 'Suburban'),
    ('Chevrolet', 'Silverado'),
    ('Chevrolet', 'Colorado'),
    ('Chevrolet', 'Camaro'),
    ('Chevrolet', 'Corvette'),
    ('Chrysler', '300'),
    ('Chrysler', 'Pacifica'),
    ('Chrysler', 'Voyager'),
    ('Dodge', 'Charger'),
    ('Dodge', 'Challenger'),
    ('Dodge', 'Hornet'),
    ('Dodge', 'Durango'),
    ('Dodge', 'Grand Caravan'),
    ('Fiat', '500'),
    ('Fiat', '500X'),
    ('Fiat', '124 Spider'),
    ('Ford', 'Mustang'),
    ('Ford', 'Escape'),
    ('Ford', 'Bronco Sport'),
    ('Ford', 'Bronco'),
    ('Ford', 'Edge'),
    ('Ford', 'Explorer'),
    ('Ford', 'Expedition'),
    ('Ford', 'F-150'),
    ('Ford', 'Ranger'),
    ('Ford', 'Maverick'),
    ('Ford', 'Transit'),
    ('Genesis', 'G70'),
    ('Genesis', 'G80'),
    ('Genesis', 'GV70'),
    ('Genesis', 'GV80'),
    ('GMC', 'Terrain'),
    ('GMC', 'Acadia'),
    ('GMC', 'Yukon'),
    ('GMC', 'Canyon'),
    ('GMC', 'Sierra'),
    ('Honda', 'Civic'),
    ('Honda', 'Accord'),
    ('Honda', 'HR-V'),
    ('Honda', 'CR-V'),
    ('Honda', 'Passport'),
    ('Honda', 'Pilot'),
    ('Honda', 'Odyssey'),
    ('Honda', 'Ridgeline'),
    ('Hyundai', 'Venue'),
    ('Hyundai', 'Elantra'),
    ('Hyundai', 'Sonata'),
    ('Hyundai', 'Kona'),
    ('Hyundai', 'Tucson'),
    ('Hyundai', 'Santa Fe'),
    ('Hyundai', 'Palisade'),
    ('Hyundai', 'Ioniq 5'),
    ('Infiniti', 'Q50'),
    ('Infiniti', 'QX50'),
    ('Infiniti', 'QX55'),
    ('Infiniti', 'QX60'),
    ('Infiniti', 'QX80'),
    ('Jeep', 'Renegade'),
    ('Jeep', 'Compass'),
    ('Jeep', 'Cherokee'),
    ('Jeep', 'Grand Cherokee'),
    ('Jeep', 'Wagoneer'),
    ('Jeep', 'Grand Wagoneer'),
    ('Jeep', 'Wrangler'),
    ('Jeep', 'Gladiator'),
    ('Kia', 'Rio'),
    ('Kia', 'Forte'),
    ('Kia', 'K4'),
    ('Kia', 'K5'),
    ('Kia', 'Soul'),
    ('Kia', 'Seltos'),
    ('Kia', 'Sportage'),
    ('Kia', 'Sorento'),
    ('Kia', 'Telluride'),
    ('Kia', 'Carnival'),
    ('Kia', 'EV6'),
    ('Land Rover', 'Discovery Sport'),
    ('Land Rover', 'Range Rover Evoque'),
    ('Land Rover', 'Range Rover Velar'),
    ('Land Rover', 'Range Rover Sport'),
    ('Lexus', 'ES'),
    ('Lexus', 'IS'),
    ('Lexus', 'NX'),
    ('Lexus', 'RX'),
    ('Lexus', 'GX'),
    ('Lexus', 'TX'),
    ('Lincoln', 'Corsair'),
    ('Lincoln', 'Nautilus'),
    ('Lincoln', 'Aviator'),
    ('Lincoln', 'Navigator'),
    ('Mazda', 'Mazda3'),
    ('Mazda', 'Mazda6'),
    ('Mazda', 'CX-30'),
    ('Mazda', 'CX-5'),
    ('Mazda', 'CX-50'),
    ('Mazda', 'CX-9'),
    ('Mazda', 'CX-90'),
    ('Mazda', 'MX-5 Miata'),
    ('Mercedes-Benz', 'A-Class'),
    ('Mercedes-Benz', 'C-Class'),
    ('Mercedes-Benz', 'E-Class'),
    ('Mercedes-Benz', 'CLA'),
    ('Mercedes-Benz', 'GLA'),
    ('Mercedes-Benz', 'GLB'),
    ('Mercedes-Benz', 'GLC'),
    ('Mercedes-Benz', 'GLE'),
    ('Mercedes-Benz', 'GLS'),
    ('Mercedes-Benz', 'EQB'),
    ('Mercedes-Benz', 'EQE'),
    ('Mini', 'Cooper'),
    ('Mini', 'Clubman'),
    ('Mini', 'Countryman'),
    ('Mitsubishi', 'Mirage'),
    ('Mitsubishi', 'Outlander Sport'),
    ('Mitsubishi', 'Eclipse Cross'),
    ('Mitsubishi', 'Outlander'),
    ('Nissan', 'Versa'),
    ('Nissan', 'Sentra'),
    ('Nissan', 'Altima'),
    ('Nissan', 'Maxima'),
    ('Nissan', 'Kicks'),
    ('Nissan', 'Rogue'),
    ('Nissan', 'Murano'),
    ('Nissan', 'Pathfinder'),
    ('Nissan', 'Armada'),
    ('Nissan', 'Frontier'),
    ('Polestar', '2'),
    ('Polestar', '3'),
    ('Porsche', 'Macan'),
    ('Porsche', 'Cayenne'),
    ('Porsche', 'Panamera'),
    ('Porsche', 'Taycan'),
    ('Porsche', '911'),
    ('Ram', '1500'),
    ('Ram', '2500'),
    ('Ram', 'ProMaster'),
    ('Ram', 'ProMaster City'),
    ('Subaru', 'Impreza'),
    ('Subaru', 'Legacy'),
    ('Subaru', 'Crosstrek'),
    ('Subaru', 'Forester'),
    ('Subaru', 'Outback'),
    ('Subaru', 'Ascent'),
    ('Tesla', 'Model 3'),
    ('Tesla', 'Model Y'),
    ('Tesla', 'Model S'),
    ('Tesla', 'Model X'),
    ('Tesla', 'Cybertruck'),
    ('Toyota', 'Corolla'),
    ('Toyota', 'Camry'),
    ('Toyota', 'Crown'),
    ('Toyota', 'Prius'),
    ('Toyota', 'RAV4'),
    ('Toyota', 'Highlander'),
    ('Toyota', '4Runner'),
    ('Toyota', 'Sienna'),
    ('Toyota', 'Tacoma'),
    ('Toyota', 'Tundra'),
    ('Toyota', 'Sequoia'),
    ('Toyota', 'Venza'),
    ('Volkswagen', 'Jetta'),
    ('Volkswagen', 'Passat'),
    ('Volkswagen', 'Arteon'),
    ('Volkswagen', 'Taos'),
    ('Volkswagen', 'Tiguan'),
    ('Volkswagen', 'Atlas'),
    ('Volkswagen', 'ID.4'),
    ('Volvo', 'S60'),
    ('Volvo', 'S90'),
    ('Volvo', 'XC40'),
    ('Volvo', 'XC60'),
    ('Volvo', 'XC90'),
    ('Volvo', 'C40 Recharge')
) as model(make, name) on model.make = cm.name
on conflict (make_id, name) do update set is_active = true;
